Import('env', 'manager')

mconf_sources = map(File, [
    'mconf.c',
    'zconf.tab.c',
    'lxdialog/checklist.c',
    'lxdialog/util.c',
    'lxdialog/inputbox.c',
    'lxdialog/textbox.c',
    'lxdialog/yesno.c',
    'lxdialog/menubox.c',
])

# Build the menu configuration utility.
env['MCONF'] = env.Program('mconf', mconf_sources,
    CCFLAGS = '-DCURSES_LOC="<ncurses.h>"',
    LIBS = ['ncurses'],
    CPPDEFINES = ['KBUILD_NO_NLS'])

# Add a config menu builder.
manager.AddTool('ConfigMenu', env['MCONF'], Action('$MCONF $SOURCE', None))

#EOF
