//! # Infinity OS Syscall
//!
//! Is a Rust library to access raw Infinity OS system calls.

#![no_std]

// export everything
pub use self::data::*;
pub use self::error::*;
pub use self::flag::*;
pub use self::number::*;
pub use self::scheme::*;

/// Complex structures that are used for some system calls
pub mod data;

/// All errors that can be generated by a system call
pub mod error;

/// All flags used on the syscalls
pub mod flag;

/// Call numbers used by each system call
pub mod number;

/// Module with the Scheme definition.
pub mod scheme;
