//! # Infinity OS Syscall
//!
//! Is a Rust library to access raw Infinity OS system calls.

#![no_std]

// export everything
pub use self::error::*;
pub use self::scheme::*;

/// All errors that can be generated by a system call
pub mod error;

/// Module with the Scheme definition.
pub mod scheme;
